### PR TITLE
feat: show the disable state on fields

### PR DESCRIPTION
**Pull request by MohammedAl-Rowad**
There are "issues" when you disable a field using the `isInitiallyDisabled` prop

 - Some fields will be disabled but the UI does not reflect that ( JSON/Rich Text/ Markdown ).
 - The user can still edit them in a way (Map/Radio).

This PR is to fix that

### CODE REVIEW

**Review by z0al — APPROVED** [review]
LGTM 👏🏻

**Review by anho — CHANGES_REQUESTED** [review]
Sorry for blocking, want to clarify something first.

**Comment by anho** [comment]
@MohammedAl-Rowad would you mind turning this into a fix version instead of a feature.

**Comment by MohammedAl-Rowad** [comment]
@anho I replaced this PR with this https://github.com/contentful/field-editors/pull/1071

**Pull request closed without merging**
