### PR TITLE
fix: add dependencies necessary for build

### PR DESCRIPTION
**Pull request by denkristoffer**
When running `yarn docz:build` I'm seeing errors about missing sub-dependencies that for whatever reason are not resolved by docz itself. Maybe a thing with `babel-preset-react-app` trying to be clever and importing them only when needed?

Errors like this one:
<details>
<summary>Details</summary>

> ./.docz/app/imports.js
> Thread Loader (Worker 0)
> [BABEL] /Users/kristoffer/field-editors/.docz/app/imports.js: Cannot find module '@babel/helper-string-parser'
> Require stack:
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/definitions/core.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/definitions/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/validators/validate.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/builders/validateNode.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/builders/generated/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/builders/react/buildChildren.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/types/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/template/lib/formatters.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/template/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/helper-function-name/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/helper-wrap-function/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/helper-remap-async-to-generator/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/plugin-proposal-async-generator-functions/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/available-plugins.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/plugins-compat-data.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/normalize-options.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/create.js
> - /Users/kristoffer/field-editors/node_modules/babel-preset-react-app/index.js
> - /Users/kristoffer/field-editors/node_modules/docz-core/node_modules/@babel/core/lib/config/files/plugins.js
> - /Users/kristoffer/field-editors/node_modules/docz-core/node_modules/@babel/core/lib/config/files/index.js
> - /Users/kristoffer/field-editors/node_modules/docz-core/node_modules/@babel/core/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/docz-core/node_modules/babel-loader/lib/index.js
> - /Users/kristoffer/field-editors/node_modules/loader-runner/lib/loadLoader.js
> - /Users/kristoffer/field-editors/node_modules/loader-runner/lib/LoaderRunner.js
> - /Users/kristoffer/field-editors/node_modules/thread-loader/dist/worker.js (While processing: "/Users/kristoffer/field-editors/node_modules/babel-preset-react-app/index.js")
>  @ ./.docz/app/root.jsx 1:100-131 1:369-376
>  @ ./.docz/app/index.jsx
>  @ multi ./.docz/app/index.jsx
>     at /Users/kristoffer/field-editors/node_modules/docz-core/dist/index.js:1306:21
> error Command failed with exit code 1.

</details>

### CODE REVIEW

**Review by z0al — COMMENTED** [review]
I feel like I'm missing context here. What problem does this solve exactly? and why did the RT snapshots change?

**Comment by denkristoffer** [comment]
Sorry @z0al, updated OP. Please feel free to validate the issue, it's a bit weird.

**Review by bgutsol — COMMENTED** [review]
@denkristoffer  I can’t reproduce the error you have, for me `yarn docz:build` works fine in master. Did you try to clean node_modules and install them from scratch?

**Comment by denkristoffer** [comment]
Okay, I'll close this and see if I can figure out what's going on.

**Pull request closed without merging**
