### PR TITLE
fix: [] Replace deprecated `*ExtensionSDK` types with `*AppSDK` types

### PR DESCRIPTION
**Pull request by colomolo**

### CODE REVIEW

**Review by ghepting — APPROVED** [review]

**Comment by ghepting** [comment]
Nice! Do we need any additional/exhaustive integration tests around these changes?

**Comment by colomolo** [comment]
> Nice! Do we need any additional/exhaustive integration tests around these changes?

It's just typings, should be fine.

**Comment by andipaetzold** [comment]
`entry-app-collapsible` still uses `*ExtensionSDK`. Should that also be replaced?

**Review by andipaetzold — CHANGES_REQUESTED** [review]
The new types were introduced in App SDK [4.17.1](https://github.com/contentful/ui-extensions-sdk/releases/tag/v4.17.1). We should bump the app-sdk version to that version

**Review by andipaetzold — APPROVED** [review]
Should we bump the version for this as we change the dependencies?

**Comment by colomolo** [comment]
> Should we bump the version for this as we change the dependencies?

Yeah, makes sense.

**Pull request merged**
