### PR TITLE
fix: clarify multiple prop

### PR DESCRIPTION
**Pull request by anho**
Minor clean up to ease consumption of reference editor.

### CODE REVIEW

**Review by DanweDE — APPROVED** [review]
:+1:

**Comment by suevalov** [comment]
Should it be a breaking change?

**Comment by anho** [comment]
> Should it be a breaking change?

Afaik we only rely internally so far, so I am bit hesitant to do that and opted-out of it. You have a strong opinion about it?

**Comment by suevalov** [comment]
@anho This property was already exposed to a function that you've introduced earlier so if to be strict - it's a breaking change. 

On the other side, we haven't achieved a major version yet so we can be less strict and make `fix: ` PR that changes API of the previously released function.

It's definitely not a chore though.

**Comment by DanweDE** [comment]
My 2 cents: Since the `CustomActionProps` wasn't previously exposed we don't necessarily have to declare it breaking. If that was the case, and `CustomActionProps` was already exposed on the top package level, then declaring a breaking change would be in order for sure. I also think it's a `fix:`.

**Review by suevalov — APPROVED** [review]

**Pull request merged**
